### ISSUE TITLE
Debugging help (empty screen)

### ISSUE THREAD

**Issue by hiteshjoshi** [aceisace/Inkycal#149]
**Describe the bug**
My EPD 7.5 V2 from Waveshare works fine with the default waveshare demo's etc. But with Inkycal the screen is always blank.

Here is my terminal output.

```
pi@raspberrypi:~ $ python3 /home/$USER/inky_run.py
inkycal_image loaded
loaded inkycal
Inkycal version: v2.0.0
Selected E-paper display: epd_7_in_5_v2
generating image(s) for Inkycal Image - show an image from a URL or local path...OK!
Inkycal version: v2.0.0
Selected E-paper display: epd_7_in_5_v2
Date: 14 Dec 20 | Time: 17:05
Generating images for all modules...successful
```

**Comment by aceisace** [comment]
@hiteshjoshi 
I think I got back to you on Discord. Can you post an update of the current progress? 
Thanks in advance!

**Comment by aceisace** [comment]
Closing issue due to lack of feedback. If you feel a need to re-open this issue, please feel free to do so again.
