### ISSUE TITLE
Calendar Works, Weather Not So much

### ISSUE THREAD

**Issue by RFNajera** [aceisace/Inkycal#154]
I followed the installer directions but kept getting a blank screen. I had selected to add a calendar, weather, and RSS feeds. Nothing appeared on the screen, so I went into the settings.json file and modified the code to show only the calendar. The calendar rendered fine.
So I went in to add the weather module and this is the error I'm getting:

```
generating image(s) for Calendar - Show monthly calendar with events from iCalendars...OK!
generating image(s) for Weather (openweathermap) - Get weather forecasts from openweathermap...Error!
Traceback (most recent call last):
  File "/home/pi/Inkycal/inkycal/main.py", line 226, in test
    black,colour=module.generate_image()
  File "/home/pi/Inkycal/inkycal/modules/inkycal_weather.py", line 315, in generate_image
    weather = self.owm.weather_at_place(self.location).weather
  File "/home/pi/.local/lib/python3.7/site-packages/pyowm/weatherapi25/weather_manager.py", line 53, in weather_at_place
    _, json_data = self.http_client.get_json(OBSERVATION_URI, params=params)
  File "/home/pi/.local/lib/python3.7/site-packages/pyowm/commons/http_client.py", line 143, in get_json
    HttpClient.check_status_code(resp.status_code, resp.text)
  File "/home/pi/.local/lib/python3.7/site-packages/pyowm/commons/http_client.py", line 288, in check_status_code
    raise exceptions.NotFoundError('Unable to find the resource')
pyowm.commons.exceptions.NotFoundError: Unable to find the resource
```

Any ideas on what is going on?

Should I not mess with the settings.json file and just try a fresh install?

I'm using a Raspberry Pi WH along with a Waveshare 7.5 black and white e paper display.

**Comment by aceisace** [comment]
@RFNajera I got back to you on Discord and the issue was resolved : )
Just for reference, the issue was caused due to an incorrect weather location.
If you are using the weather by ID,please enter only the digits at the end of a URL.
Otherwise, please use the following format: Cityname, Countrycode
