### ISSUE TITLE
Suggestion: Support for Raspberry Pi OS Minimal -> python3-pip

### ISSUE THREAD

**Issue by surak** [aceisace/Inkycal#173]
Same story as #172 , install won't work until python3-pip is installed, and it doesn't come with the latest raspbian-minimal as of feb.2020 yet.

I use minimal because it's a machine that is only there for the calendar.

**Comment by aceisace** [comment]
I think the answer to this is the same as #172 . Instead of fully supporting a fast-changing OS with minimal packages, a better solution would be to provide a page on the wiki. I'm closing this issue as the fix will be provided in the mentioned issue.
