### ISSUE TITLE
24-hour-format for openweathermap not localized

### ISSUE THREAD

**Issue by maweki** [aceisace/Inkycal#178]
**Describe the bug**
The 24 h format for openweathermap is not localized.

**To Reproduce**
Choose any localization that does not use `.` as a seperator between hour and minute, like `de` (german). It shows `3.00`, for example.

**Expected behavior**
Should show `3:00`

**Screenshots**

**Additional context**
Issue is here:
https://github.com/aceisace/Inkycal/blob/main/inkycal/modules/inkycal_weather.py#L364

I'll try to fix it myself.

Edit: maybe it's just wrong. In other places the colon is used for 24h
https://github.com/aceisace/Inkycal/blob/main/inkycal/modules/inkycal_weather.py#L434

what's the expected behaviour?

**Comment by aceisace** [comment]
Thanks for reporting this @maweki . It's actually not an issue, but something between trial-and-error and user-preference.
Using `:` as a separator can lead to some issues when rendering text in a weather module with limited space, (height too small or display width limited). So in some cases, letters would be merged together with the top dot of `:`, which was clearly not desired.

As a result, a simple dot symbol has been used to improve the rendering. Yet again, it's something of a user-preference (e.g. on larger displays which don't have this issue, so it's up to the user to change it as desired.

I'm closing this issue as it won't be worked on. Thank you for your understanding and apologies for the inconvenience.

Should you feel a need to re-open this issue, please feel free to do so.
