### ISSUE TITLE
Duplicate ical entries from different sources

### ISSUE THREAD

**Issue by guerda** [aceisace/Inkycal#215]
**Describe the bug**
If two ical calendar sources contain the same event (e.g. one as invitee, one as organizer), the ical agenda shows them duplicate, even if the UID is the same.

**To Reproduce**
1. Create two ICS files with the same event (same UID)
2. Setup agenda module with both ICS files.
3. Start inkycal

**Expected behavior**
Only one instance of this event is shown

**Comment by aceisace** [comment]
Thanks for the details. Just writing some info for when I implement this officially
* Parse all events
* Convert List->Set->List to remove duplicate entries
* Write test for this case
