### ISSUE TITLE
Inkycal e-paper 9.7 

### ISSUE THREAD

**Issue by Engel56** [aceisace/Inkycal#220]
Raspberrypi zero w.  "Waveshare e-paper 9.7"
Raspi os aktuell

Initialising..Updating display...oops, somthing didn't work right :/

was nun?

**Comment by aceisace** [comment]
Welcher branch ist das? Main oder feature/venv ? In main Zweig müssen zusätzliche Sachen installiert werden, daher empfehle ich den feature/venv branch.

**Comment by Engel56** [comment]
Hallo
Wollte nur danke sagen.
Mit ihrer info feature/venv  läufst es einwandfrei.
Kaffe ist unterwegs

**Comment by aceisace** [comment]
Gern geschehen 😄 
Vielen Dank für den Kaffee! Freut mich zu hören, dass feature/venv wie erwartet funktioniert
