### ISSUE TITLE
Todoist out of available lines

### ISSUE THREAD

**Issue by dicijr** [aceisace/Inkycal#222]
This is probably a case of me not understanding the entire way this works. I am looking to just use the Todoist API to display different Todos. However, I can only display 6 lines at a time. I'm trying to tweak to code to let the module use the entire length of the display but it is not working.. Any guidance?

**Comment by aceisace** [comment]
Closing issue as it has been resolved some time ago. If you feel a need to re-open this issue, please feel free to do so.
