### ISSUE TITLE
Feature request: add portuguese language option in Web-UI

### ISSUE THREAD

**Issue by djairjr** [aceisace/Inkycal#223]
Please, how can I help translating InkyCal to Portuguese Brazil? What files can I move to do this job?

**Comment by aceisace** [comment]
Hi, Inkycal does have built-in support for multiple languages, but not all are directly accessible. Which parts need translating?

**Comment by djairjr** [comment]
I'm sorry, man. The Web interface (Web-UI) does not discriminate the Portuguese language. But I went through the configuration files and got the calendar in my language. I Web-UI section "Common module settings" does not have the Portuguese setting in language. To setup this language you just need to put pt on config file.

**Comment by aceisace** [comment]
Hi again,
I've added the Portuguese language as an option in the web-ui:
![Bildschirm­foto 2023-01-13 um 20 45 39](https://user-images.githubusercontent.com/29558518/212405828-06e53042-6c45-47f3-adb0-098e3e150ae5.png)

Please check if it is working as expected 👍

**Comment by aceisace** [comment]
Closing as issue seems stale. If you need to re-open this issue, please feel free to do so
