### ISSUE TITLE
Feature request: support for 12.48" v2

### ISSUE THREAD

**Issue by ch3lmi** [aceisace/Inkycal#243]
This is a feature request to support the newer [V2 Colour Waveshare Display ](https://www.waveshare.com/product/12.48inch-e-paper-module-b.htm#none;)

I have the driver file available and can created a PR if you create a branch for this issue

**Comment by aceisace** [comment]
@ch3lmi Thanks for the issue with the feature request. Yes please, you can target the branched linked with this issue, which is the `feature/243` branch

**Comment by achi87** [comment]
Thanks a lot!
That's a massive improvement of red colour content.
